### ISSUE TITLE
File uploads: additional types and size increase

### ISSUE THREAD

**Issue by AntoineAugusti** [cds-snc/notification-documentation#27]
We should document that new files are supported and max size has been bumped from 2MB to 10MB.

List of supported types: https://github.com/cds-snc/notification-document-download-api/blob/a4edb5a5984be248639e159ef584ce3cfa1a3b73/app/config.py#L16-L27

https://github.com/cds-snc/notification-document-download-api/pull/20

**Comment by anikbrazeau** [comment]
Change reflected in PRs:
https://github.com/cds-snc/notification-documentation/pull/34
https://github.com/cds-snc/notification-documentation/pull/14
