### ISSUE TITLE
French page names

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/notification-documentation#39]
Renaming files for french page url:

notification-documentation/src/fr/

- callbacks.md ---> rappel.md
- keys.md ---> cles.md
- limits.md ---> limites.md
- send.md ---> envoyer.md
- start.md ---> commencer.md
- status.md ---> etat.md
- testing.md ---> essai.md

Q: is it okay if pages are the same in EN and FR (ex: architecture.md)

**Comment by AntoineAugusti** [comment]
> Q: is it okay if pages are the same in EN and FR (ex: architecture.md)

No problem at all!
