### ISSUE TITLE
Add 'Edit this page on GitHub' to the main page (README.md)

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/notification-documentation#42]

**Comment by AntoineAugusti** [comment]
If you want people to be able to propose changes to this page, you can remove the metadata at the very beginning of

https://github.com/cds-snc/notification-documentation/blob/main/src/en/README.md
https://github.com/cds-snc/notification-documentation/blob/main/src/fr/README.md

The part with `editLinks: false`
